Repository BeyondMafia/BeyondMafia-Integration, pull requests merged in 2023-02, with the labels that each got.

#184 [TESTED] pulled out commonly used code
  Games/core/Role.js
  Games/types/Mafia/Action.js
  Games/types/Mafia/Role.js
  Games/types/Mafia/effects/Stun.js
  Games/types/Mafia/roles/cards/NightNurse.js
  Games/types/Mafia/roles/cards/NightRoleBlocker.js
  Games/types/Mafia/roles/cards/NightSaver.js
Labels: enhancement

#238 orange now counts as food for famine
  Games/types/Mafia/effects/Famished.js
Labels: refactor

#266 [fixed & tested] added chef by riskitforthebiscuit + exclusive meetings by rend
  Games/core/Meeting.js
  Games/core/Player.js
  Games/types/Mafia/const/MeetingPriority.js
  Games/types/Mafia/const/Priority.js
  Games/types/Mafia/items/Handcuffs.js
  Games/types/Mafia/items/Invitation.js
  Games/types/Mafia/items/Orange.js
  Games/types/Mafia/roles/Village/Capybara.js
  Games/types/Mafia/roles/Village/Chef.js
  Games/types/Mafia/roles/cards/BanquetInvite.js
  Games/types/Mafia/roles/cards/JailTarget.js
  Games/types/Mafia/roles/cards/OrangeGiver.js
  data/roles.js
Labels: enhancement

#253 Added Graverobber
  Games/types/Mafia/items/Bomb.js
  Games/types/Mafia/items/Flier.js
  Games/types/Mafia/items/Gasoline.js
  Games/types/Mafia/items/Handcuffs.js
  Games/types/Mafia/items/Match.js
  Games/types/Mafia/items/Suit.js
  Games/types/Mafia/roles/Mafia/Graverobber.js
  Games/types/Mafia/roles/cards/RobGrave.js
  data/roles.js
Labels: enhancement

#249 bugfix: dreaming about self
  Games/types/Mafia/roles/cards/Dream.js
Labels: bug

#173 [TESTED] added diabolist
  Games/types/Mafia/effects/CursedVote.js
  Games/types/Mafia/roles/Mafia/Diabolist.js
  Games/types/Mafia/roles/cards/CurseVote.js
  Games/types/Mafia/templates/death.js
  data/roles.js
Labels: enhancement

#268 [bugfix] fixed role target meetings
  Games/core/Meeting.js
  Games/types/Mafia/roles/cards/TailorSuit.js
Labels: bug

#244 refactor priority: use more default values (priority 100)
  Games/types/Mafia/const/Priority.js
  Games/types/Mafia/roles/cards/Carol.js
  Games/types/Mafia/roles/cards/Dream.js
  Games/types/Mafia/roles/cards/GiveVisitorsGuns.js
  Games/types/Mafia/roles/cards/LearnVisitors.js
  Games/types/Mafia/roles/cards/MakeVisitorsInsane.js
  Games/types/Mafia/roles/cards/TrackPlayer.js
  Games/types/Mafia/roles/cards/WatchPlayer.js
Labels: refactor

#191 Loudmouth submission
  Games/types/Mafia/const/Priority.js
  Games/types/Mafia/roles/Village/Babushka.js
  Games/types/Mafia/roles/Village/Loudmouth.js
  Games/types/Mafia/roles/cards/CryOutVisitors.js
  Games/types/Mafia/roles/cards/EnqueueVisitors.js
  Games/types/Mafia/roles/cards/KillVisitors.js
  data/roles.js
  test/Games/Mafia.test.js
Labels: enhancement, refactor

#248 bugfix: add dominates check for mismason and jail kills
  Games/types/Mafia/roles/cards/DieIfMasonsConvertMafia.js
  Games/types/Mafia/roles/cards/JailTarget.js
Labels: bug

#260 Added message giver default to priority exports
  Games/types/Mafia/const/Priority.js
Labels: bug

#321 Minor role fixes
  Games/types/Mafia/roles/cards/HuntPrey.js
  Games/types/Mafia/roles/cards/WinIfTargetDead.js
Labels: bug

#185 [TESTED] added prophet
  Games/core/Game.js
  Games/types/Mafia/roles/Independent/Prophet.js
  Games/types/Mafia/roles/cards/Prognosticate.js
  Games/types/Mafia/roles/cards/WinIfPrescient.js
  data/roles.js
Labels: enhancement

#325 Removed multimeeting from chef
  Games/types/Mafia/roles/cards/BanquetInvite.js
Labels: bug

#323 Fixed dead dream.
  Games/types/Mafia/roles/cards/Dream.js
Labels: bug

#271 added clown and gave jester a meeting
  Games/types/Mafia/roles/Independent/Jester.js
  Games/types/Mafia/roles/Mafia/Clown.js
  Games/types/Mafia/roles/cards/ClownAround.js
  Games/types/Mafia/roles/cards/FoolAround.js
  data/roles.js
Labels: enhancement

#256 increased gay emote resolution
  react_main/public/images/emotes/gay.gif
  react_main/public/images/emotes/gay.png
  react_main/src/components/Emotes.jsx
Labels: refactor

#328 randomized banquet message
  Games/types/Mafia/items/Invitation.js
Labels: bug

#155 added-mastermind
  Games/types/Mafia/const/Priority.js
  Games/types/Mafia/roles/Independent/Mastermind.js
  Games/types/Mafia/roles/cards/AnonymizeMafia.js
  Games/types/Mafia/roles/cards/WinInsteadOfMafia.js
  data/roles.js
Labels: enhancement

#273 added king
  Games/types/Mafia/roles/Village/King.js
  data/roles.js
Labels: enhancement

#327 docs: add guide on contributing role icons
  README.md
  docs/role-icons.md
Labels: documentation

#251 feat: add sorceror + text input
  Games/core/Meeting.js
  Games/types/Mafia/effects/Cursed.js
  Games/types/Mafia/roles/Mafia/Sorceror.js
  Games/types/Mafia/roles/cards/CurseWithWord.js
  Games/types/Mafia/templates/death.js
  data/roles.js
  react_main/src/Constants.jsx
  react_main/src/pages/Game/Game.jsx
Labels: enhancement

#267 fix: rehosting a game (main page) chooses the correct lobby (instead of MAIN every time)
  react_main/src/pages/Play/Join.jsx
Labels: bug

#337 fix: forbid editing other people's profile (FE only)
  react_main/src/pages/User/Profile.jsx
Labels: bug

#338 chore: address mongodb deprecation warnings
  db/db.js
Labels: refactor

#289 Whispers leak now!
  Games/core/Meeting.js
  lib/Random.js
Labels: bug

#336 assets(role icon): added icons for chef, justice, lk, cyclist, thing, ninja, graverobber
  react_main/public/images/roles.png
  react_main/src/css/roles.css
Labels: enhancement

#318 added tinkerer and slasher
  Games/types/Mafia/roles/Mafia/Slasher.js
  Games/types/Mafia/roles/Village/Tinkerer.js
  Games/types/Mafia/roles/cards/DayShooter.js
  Games/types/Mafia/roles/cards/DaySlasher.js
  data/roles.js
Labels: enhancement

#319 added santa
  Games/types/Mafia/roles/Village/Santa.js
  Games/types/Mafia/roles/cards/GivePresents.js
  Games/types/Mafia/roles/cards/NaughtyOrNice.js
  data/roles.js
Labels: enhancement

#309 Added informant
  Games/types/Mafia/roles/Mafia/Informant.js
  Games/types/Mafia/roles/cards/ReceiveReports.js
  data/roles.js
Labels: enhancement

#189 feat: add dark mode
  db/schemas.js
  react_main/build/asset-manifest.json
  react_main/build/index.html
  react_main/build/precache-manifest.34f70a6d7b3df09b484b2032b27ec2ce.js
  react_main/build/precache-manifest.84b14d494f02c854fb1b84d9060450dc.js
  react_main/build/service-worker.js
  react_main/build/static/css/main.9f1c9d3c.chunk.css
  react_main/build/static/css/main.9f1c9d3c.chunk.css.map
  react_main/build/static/css/main.a7d5bf30.chunk.css
  react_main/build/static/css/main.a7d5bf30.chunk.css.map
  react_main/build/static/js/2.b401c555.chunk.js
  react_main/build/static/js/2.b401c555.chunk.js.LICENSE.txt
  react_main/build/static/js/2.bfa0ae91.chunk.js
  react_main/build/static/js/2.bfa0ae91.chunk.js.LICENSE.txt
  react_main/build/static/js/main.743c9df7.chunk.js
  react_main/build/static/js/main.743c9df7.chunk.js.LICENSE.txt
  react_main/build/static/js/main.743c9df7.chunk.js.map
  react_main/build/static/js/main.e0146d7e.chunk.js
  react_main/build/static/js/main.e0146d7e.chunk.js.LICENSE.txt
  react_main/build/static/js/main.e0146d7e.chunk.js.map
  react_main/src/Main.jsx
  react_main/src/css/alerts.css
  react_main/src/css/chat.css
  react_main/src/css/comments.css
  react_main/src/css/createSetup.css
  react_main/src/css/form.css
  react_main/src/css/forums.css
  react_main/src/css/game.css
  react_main/src/css/host.css
  react_main/src/css/join.css
  react_main/src/css/learn.css
  react_main/src/css/main.css
  react_main/src/css/markdown.css
  react_main/src/css/moderation.css
  react_main/src/css/play.css
  react_main/src/css/popover.css
  react_main/src/css/roles.css
  react_main/src/css/setup.css
  react_main/src/css/shop.css
  react_main/src/css/user.css
  react_main/src/css/userSearch.css
  react_main/src/pages/Chat/Chat.jsx
  react_main/src/pages/Game/Game.jsx
  react_main/src/pages/User/Settings.jsx
  react_main/src/pages/User/User.jsx
  react_main/src/utils.jsx
Labels: enhancement

#254 feat: add illusionist and catlady
  Games/types/Mafia/items/Cat.js
  Games/types/Mafia/items/Gun.js
  Games/types/Mafia/roles/Mafia/CatLady.js
  Games/types/Mafia/roles/Mafia/Illusionist.js
  Games/types/Mafia/roles/cards/CatGiver.js
  Games/types/Mafia/roles/cards/GunFramer.js
  data/roles.js
Labels: enhancement

#180 added invisible man
  Games/types/Mafia/roles/Village/InvisibleMan.js
  Games/types/Mafia/roles/cards/Eavesdrop.js
  data/roles.js
Labels: enhancement

#368 feat: add kickvoting
  Games/core/Meeting.js
Labels: bug

#356 refactor: increased secondary timer from 30s to 1minute
  Games/types/Mafia/meetings/Village.js
Labels: enhancement

#342 feat: add messenger/ courier + visitor/ trespasser from forum mafia
  Games/types/Mafia/roles/Independent/Jester.js
  Games/types/Mafia/roles/Mafia/Courier.js
  Games/types/Mafia/roles/Mafia/Trespasser.js
  Games/types/Mafia/roles/Village/Messenger.js
  Games/types/Mafia/roles/Village/Visitor.js
  Games/types/Mafia/roles/cards/MessageSender.js
  Games/types/Mafia/roles/cards/Visit.js
  data/roles.js
Labels: enhancement

#391 Fixed king
  Games/types/Mafia/roles/Village/King.js
  Games/types/Mafia/roles/Village/VillageIdiot.js
  Games/types/Mafia/roles/cards/SeeRandomSpeakers.js
Labels: bug, refactor

#403 Fixes errors in roles.js data
  data/roles.js
Labels: bug, Requested / High priority

#402 Fixed santa witch
  Games/types/Mafia/roles/cards/GivePresents.js
  Games/types/Mafia/roles/cards/RedirectAction.js
Labels: bug
