Repository BeyondMafia/BeyondMafia-Integration, pull requests merged in 2023-03, with the labels that each got.

#408 bugfix: fix targets for messengesender and visit
  Games/types/Mafia/roles/cards/MessageSender.js
  Games/types/Mafia/roles/cards/Visit.js
Labels: bug

#417 bugfix: check null suit for tailor
  Games/types/Mafia/roles/cards/TailorSuit.js
Labels: bug

#414 bugfix: fix jester test case
  Games/types/Mafia/roles/cards/WinIfLynched.js
  test/Games/Mafia.test.js
Labels: bug

#409 bugfix: add babushka conversion immunity
  Games/types/Mafia/roles/Village/Babushka.js
  Games/types/Mafia/roles/cards/ConvertImmune.js
  Games/types/Mafia/roles/cards/MimicRole.js
  Games/types/Mafia/roles/cards/SwapRoles.js
  data/roles.js
Labels: bug

#366 docs: add constants into documentation
  docs/guide-role-creation.md
  docs/guide-role-icons.md
  docs/info-mafia-constants.md
  docs/setup-bot-games.md
  docs/setup-dependencies.md
  docs/setup-mongo-redis-docker.md
Labels: documentation

#430 Added emotes: tip and tipb
  react_main/public/images/emotes/tip.gif
  react_main/public/images/emotes/tipb.gif
  react_main/src/components/Emotes.jsx
Labels: enhancement

#425 Add rainbow text to party meeting
  react_main/build/asset-manifest.json
  react_main/build/index.html
  react_main/build/precache-manifest.f1975892a5ac75fca74989a1c63b6712.js
  react_main/build/service-worker.js
  react_main/build/static/css/main.16163d33.chunk.css
  react_main/build/static/css/main.16163d33.chunk.css.map
  react_main/build/static/js/main.32a14c6d.chunk.js
  react_main/build/static/js/main.32a14c6d.chunk.js.LICENSE.txt
  react_main/build/static/js/main.32a14c6d.chunk.js.map
  react_main/src/css/game.css
  react_main/src/pages/Game/Game.jsx
Labels: enhancement

#431 bugfix(mummy): do not trigger abilities the night it is killed
  Games/types/Mafia/roles/cards/KillVisitorsWhileDead.js
Labels: bug

#429 feat(stealItems): add robinhood, thief, waitress, housekeeper and stealItems library
  Games/types/Mafia/Action.js
  Games/types/Mafia/const/Priority.js
  Games/types/Mafia/roles/Mafia/Housekeeper.js
  Games/types/Mafia/roles/Mafia/Thief.js
  Games/types/Mafia/roles/Village/RobinHood.js
  Games/types/Mafia/roles/Village/Waitress.js
  Games/types/Mafia/roles/cards/KeepHouse.js
  Games/types/Mafia/roles/cards/RobGrave.js
  Games/types/Mafia/roles/cards/StealItem.js
  Games/types/Mafia/roles/cards/StealItemsAndBlock.js
  Games/types/Mafia/roles/cards/TransferItems.js
  data/roles.js
Labels: enhancement

#411 bugfix: allow filtering during anon meetings
  react_main/src/pages/Game/Game.jsx
Labels: bug

#303 docs: add github codespace documentation
  README.md
  docs/github-codespace.md
  docs/setup-dependencies.md
  docs/setup-mongo-redis-docker.md
Labels: documentation

#415 bugfix: fix setup searching for page > 1
  react_main/src/pages/Play/Host/Host.jsx
Labels: bug

#283 [Resistance] added avalon roles
  Games/types/Resistance/Game.js
  Games/types/Resistance/Role.js
  Games/types/Resistance/roles/Resistance/Merlin.js
  Games/types/Resistance/roles/Resistance/Percival.js
  Games/types/Resistance/roles/Spies/Morgana.js
  Games/types/Resistance/roles/Spies/Oberon.js
  Games/types/Resistance/roles/Spies/Spy.js
  Games/types/Resistance/roles/cards/Foresight.js
  Games/types/Resistance/roles/cards/KnowMerlin.js
  Games/types/Resistance/roles/cards/Oblivious.js
  Games/types/Resistance/roles/cards/SpyCore.js
  Games/types/Resistance/roles/cards/TeamCore.js
  data/roles.js
  react_main/src/pages/Game/ResistanceGame.jsx
Labels: enhancement

#276 feat: add Governor Role + anonymousVotes Meeting flag
  Games/core/Meeting.js
  Games/core/Player.js
  Games/types/Mafia/const/Priority.js
  Games/types/Mafia/items/OverturnSpectator.js
  Games/types/Mafia/roles/Village/Governor.js
  Games/types/Mafia/roles/cards/LynchRevenge.js
  Games/types/Mafia/roles/cards/OverturnVote.js
  data/roles.js
  react_main/src/css/roles.css
Labels: enhancement

#272 added clockmaker
  Games/types/Mafia/effects/ExtraLife.js
  Games/types/Mafia/roles/Independent/Clockmaker.js
  Games/types/Mafia/roles/cards/WinAtMidnight.js
  data/roles.js
Labels: enhancement

#305 Added Trickster
  Games/types/Mafia/Action.js
  Games/types/Mafia/items/Crystal.js
  Games/types/Mafia/items/CursedArmor.js
  Games/types/Mafia/items/CursedKnife.js
  Games/types/Mafia/items/CursedSnowball.js
  Games/types/Mafia/items/Knife.js
  Games/types/Mafia/roles/Village/Trickster.js
  Games/types/Mafia/roles/cards/TrickedWares.js
  data/roles.js
Labels: enhancement

#401 Fix witch veg bug
  Games/core/Game.js
  Games/types/Mafia/Game.js
  Games/types/Mafia/meetings/Village.js
Labels: bug, Requested / High priority

#444 Added Graveyard Participation
  data/roles.js
Labels: bug, enhancement

#451 bugfix: incorrect varname in seeUnvote
  Games/core/Player.js
Labels: bug, Requested / High priority

#467 Profile video
  db/schemas.js
  react_main/src/css/user.css
  react_main/src/pages/User/Profile.jsx
  react_main/src/pages/User/Settings.jsx
  react_main/src/pages/User/User.jsx
  routes/user.js
Labels: enhancement

#462 bugfix: tinkerer does not give gun from voteoff
  Games/types/Mafia/roles/cards/DayShooter.js
Labels: bug

#465 bugfix: add uncontrollable label for delayed actions
  Games/types/Mafia/effects/Poison.js
  Games/types/Mafia/roles/cards/RedirectAction.js
  Games/types/Mafia/roles/cards/SwapVisitors.js
  docs/info-mafia-constants.md
Labels: bug

#472 refactor: increase tick from 5s to 15s
  react_main/src/pages/Game/Game.jsx
Labels: refactor

#463 bugfix: do not show disabled roles on search
  react_main/src/components/Roles.jsx
Labels: bug

#498 Fix role description
  data/roles.js
Labels: refactor

#505 added ratjam
  react_main/public/images/emotes/ratjam.gif
  react_main/src/components/Emotes.jsx
Labels: enhancement

#513 Bday
  Games/core/Player.js
  Games/core/User.js
  Games/games.js
  data/constants.js
  db/schemas.js
  modules/redis.js
  react_main/package.json
  react_main/src/components/Form.jsx
  react_main/src/css/form.css
  react_main/src/pages/Game/Game.jsx
  react_main/src/pages/User/Settings.jsx
  routes/shop.js
  routes/user.js
Labels: enhancement

#448 feat(vote): re-enable click to vote
  react_main/src/pages/Game/Game.jsx
Labels: enhancement

#537 bugfix: do not shatter armour if healed
  Games/types/Mafia/items/Armor.js
Labels: bug

#499 docs: fix broken links in readme
  README.md
  docs/guide-role-icons.md
  docs/setup-github-codespace.md
Labels: documentation

#560 bugfix: do not allow dreamer to receive dreams on dead
  Games/types/Mafia/roles/cards/Dream.js
Labels: bug, game/mafia

#460 bugfix(textinput): replace newlines with space
  react_main/src/pages/Game/Game.jsx
Labels: bug, frontend/ui

#590 Add framer role
  Games/types/Mafia/const/Priority.js
  Games/types/Mafia/roles/Mafia/Framer.js
  Games/types/Mafia/roles/cards/MakeGuilty.js
  Games/types/Mafia/roles/cards/MakeInnocent.js
  data/roles.js
Labels: enhancement, game/mafia

#564 bugfix(thulu, watcher): use getVisitors to properly check for hidden visitors and multimeeting visitors
  Games/types/Mafia/Action.js
  Games/types/Mafia/roles/cards/MakeVisitorsInsane.js
  Games/types/Mafia/roles/cards/WatchPlayer.js
Labels: bug, game/mafia
